language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - PACKAGE="cstruct" OCAML_VERSION=latest POST_INSTALL_HOOK="opam install tls"
  - PACKAGE="cstruct" OCAML_VERSION=4.02 DEPOPTS="lwt" POST_INSTALL_HOOK="opam install dns irmin"
  - PACKAGE="cstruct" OCAML_VERSION=4.02 DEPOPTS="async"
  - PACKAGE="cstruct" OCAML_VERSION=4.01 DEPOPTS="async lwt" POST_INSTALL_HOOK="opam install mirage"
  - PACKAGE="cstruct" OCAML_VERSION=4.01 DEPOPTS="camlp4"
