language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PACKAGE="cstruct.9999"
  - DEPOPTS="ppx_tools async lwt"
  - REVDEPS="tls dns irmin tcpip"
  matrix:
  - DISTRO="debian-stable" OCAML_VERSION="4.02.3"
  - DISTRO="debian-testing" OCAML_VERSION="4.03.0"
  - DISTRO="debian-unstable" OCAML_VERSION="4.04.0"
  - DISTRO="ubuntu-14.04" OCAML_VERSION="4.02.3"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.05.0"
  - DISTRO="centos-7" OCAML_VERSION="4.03.0"
  - DISTRO="centos-6" OCAML_VERSION="4.02.3"
  - DISTRO="alpine-3.5" OCAML_VERSION="4.04.0"
  - DISTRO="fedora-24" OCAML_VERSION="4.03.0"
  - DISTRO="opensuse-42.2" OCAML_VERSION="4.04.0"
